steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}",
        "${_SERVICE_FOLDER}",
      ]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]
    
  - id: 'tf init'
    name: 'hashicorp/terraform:0.15.3'
    entrypoint: 'sh'
    args: 
    - '-c'
    - |
        cd terraform-serverless && terraform init

  - id: 'tf apply'
    name: 'hashicorp/terraform:0.15.3'
    entrypoint: 'sh'
    args: 
    - '-c'
    - | 
        cd terraform-serverless && chmod a+x scripts/get_latest_tag.sh && terraform apply -auto-approve -var project=terraform-training-315200

substitutions:
  _SERVICE_FOLDER: terraform-serverless/service
  _SERVICE_NAME: cats

images:
  - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"
